### ISSUE TITLE
Fix progress tracker

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/BC-Wallet-Demo#100]
The tracker at the top of the screen also doesn’t seem to advance proportionally.

**Comment by cvarjao** [comment]
Needs to figure out what steps we want to show in the progress bar

**Comment by hannahgov** [comment]
Need to discuss with Wade on if what I want is possible. I've put what I would like [here](https://app.mural.co/t/digitalidentityandtrust0399/m/digitalidentityandtrust0399/1666280189047/211ffe0c9036c7987b551dd096f9c29d6b7ef1fb?wid=0-1667333803058).

**Comment by wadeking98** [comment]
We may need to look at separating the lawyer and student showcases in order to achieve this

**Comment by wadeking98** [comment]
Blocked by #121
