### ISSUE TITLE
Next and Back buttons are out of frame

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/BC-Wallet-Demo#101]
The next and back buttons are out of frame. see screenshots below. 
![Screen Shot 2022-11-01 at 9.22.29 AM.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/90ac4ae7-4945-4ae5-9a5c-17823dfecefc)

![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/9b94f7e0-a150-4e4d-8ab8-f029145ccd11)

![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/eabe3cd5-d3cc-4156-8a69-8c6e3d92a24b)

**Comment by knguyenBC** [comment]
@hannahgov It looks like it might be fixable if we reduce the content. Would it be easier to make the content here shorter?

**Comment by hannahgov** [comment]
I guess there's no way to make the image smaller to fit the bars?

**Comment by wadeking98** [comment]
We can make the image smaller, but that also means the QR code will take up more of the image

**Comment by hannahgov** [comment]
I guess you can't make the QR smaller too
