### ISSUE TITLE
Update the Person credential card design

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/BC-Wallet-Demo#102]
Current screenshot of the Person credential
![20221101_101437.jpg](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/df24f681-c34e-4a21-8777-7291574ed014)

The credential should be rendered using the test person credential design
[Find assets in this google drive](https://drive.google.com/open?id=19clGi2vJq-CGolkOnmlz8IEssPioHvfd&authuser=kimberly.nguyen.gov.bc%40gmail.com&usp=drive_fs)
Please use filename: Test-Person-Credential-Bkgrd.png

**Comment by cvarjao** [comment]
Make sure you are using build 479+
