### ISSUE TITLE
A 500 error appears going through the demo

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/BC-Wallet-Demo#109]
A 500 error appears going through the demo

![Screen Shot 2022-11-01 at 9.28.31 AM.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/d35c1b61-0197-4f04-868c-7c9331330b2c)

**Comment by wadeking98** [comment]
I believe this PR resolved the issue: https://github.com/bcgov/BC-Wallet-Demo/pull/116
