### ISSUE TITLE
Lawyer use case demo credential show wrong issuer and verifier logo

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/BC-Wallet-Demo#151]
![20230306_164311.jpg](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/57563155-a366-40c4-bddb-021130512b48)

![20230306_164311.jpg](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/4f6b1db3-af2b-4490-9d03-8bb207a318e4)

![20230306_164442.jpg](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/ce294695-dabd-4b41-a0f6-d3621c437330)

**Comment by cvarjao** [comment]
fixed
