### ISSUE TITLE
Update "Revoking your credentials" section

### ISSUE THREAD

**Issue by cvarjao** [bcgov/BC-Wallet-Demo#171]
Make them smaller and a bit more hidden

Here are wireframes for simple UI updates.
Concept 1:
https://xd.adobe.com/view/641340e7-beb5-40af-baf1-16da41349f67-3140/

Concept 2:
https://xd.adobe.com/view/ab13ebb0-8f76-4854-82dc-a205b6b23d3a-fe40/

Choose whichever is easier.

The revocation flow for the showcase would need further review for future updates.

**Comment by knguyenBC** [comment]
I'll provide some wireframes for this. Thinking a crawl walk run format.

**Comment by knguyenBC** [comment]
Added wireframes.
