### ISSUE TITLE
Demo person credential atttribute issues

### ISSUE THREAD

**Issue by bryce-mcmath** [bcgov/BC-Wallet-Demo#199]
When getting a demo person credential from the prod showcase, two attributes have issues:
 - The image doesn't show up
 - The date of birth is very far into the future

See attached:
![empty_image_attr.png](https://images.zenhubusercontent.com/63bc52dfbcde5d544793e7d3/76edc786-1239-4afb-98f4-50db4c79e628)
![date_birth_attr.png](https://images.zenhubusercontent.com/63bc52dfbcde5d544793e7d3/f08bafc9-a387-4577-b7db-a2abb13948e1)

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/839
