### ISSUE TITLE
Lawyer showcase is sending two person credential offers when using deep link

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/BC-Wallet-Demo#224]
### Description of problem
Lawyer showcase is sending two person credential offers when using deep link

### Expected behavior
Should only send one

### Steps to reproduce
- Open the lawyer showcase on a single mobile device
- Follow the lawyer showcase and acquire the Person credential
- After acquiring the person credential, check the notifications list
- You'll see an additional offer

### Environment
- [ ] Occurs on Android
- [X] Occurs on iOS

Build #: 1230

Android Device Model: 

iOS Device Model: iPhone SE

### Severity
- [ ] High
- [ ] Medium
- [X] Low

**Comment by cvarjao** [comment]
need to be re-tested

**Comment by jleach** [comment]
I tested this withe the current production release (1.0.16) and it works as expected. Using the Showcase lawyer example I only received a single credential on both my tests.
