### ISSUE TITLE
Cool Clothes Online - Proof Request not asking for expiration up to today

### ISSUE THREAD

**Issue by cvarjao** [bcgov/BC-Wallet-Demo#37]
When using the Cool Clothes Online, the proof request seems to be asking for a valid credential with an expire date `> 20220707` (this was tested on July 21). Shouldn't it be  `>= 20220721` (today's date)?

**Comment by cvarjao** [comment]
@wadeking98 , is this updated in TEST? it is still a month or so off.

**Comment by wadeking98** [comment]
I've added a new PR, I thought I fixed it last time but I guess not. This new PR should fix it though
