### ISSUE TITLE
Ask for Feedback at the end

### ISSUE THREAD

**Issue by cvarjao** [bcgov/BC-Wallet-Demo#45]
Automatically prompt this pop-up at the end of the demo (after they have completed both scenarios).

Wireframe: https://xd.adobe.com/view/eaef015c-6785-41a9-bdc5-10e863ce9e1e-bfbc/ 

- Link to survey TBD

**Comment by wadeking98** [comment]
Should we send the feedback via email? We don't have a database in the application

**Comment by cvarjao** [comment]
No, the demo will just provide a link to survey at the end. The survey already exists

**Comment by knguyenBC** [comment]
@hannahgov let me know if this works.
