### ISSUE TITLE
Expose demo URL under digital.gov.bc.ca

### ISSUE THREAD

**Issue by cvarjao** [bcgov/BC-Wallet-Demo#48]
URL: https://digital.gov.bc.ca/digital-trust/demo

**Comment by wadeking98** [comment]
john jordan and stephen curran want the url to be `https://digital.gov.bc.ca/digital-trust/demo`

**Comment by cvarjao** [comment]
@wadeking98 , can we update to be `/digital-trust/showcase`?

**Comment by wadeking98** [comment]
deployed to https://digital.gov.bc.ca/digital-trust/showcase
