### ISSUE TITLE
Update BC Wallet instructions to use app store

### ISSUE THREAD

**Issue by cvarjao** [bcgov/BC-Wallet-Demo#52]
### Content (desktop):
**1. Download BC Wallet on your phone**
To download, scan the QR code on your phone or select the apps store icon below. You can also search for BC Wallet in your phone's apps store.

**2. Complete the setup**
Complete the onboarding process and setup up your PIN.

### Content (mobile)

**1. Download BC Wallet on your phone**
To download, select the apps store icon below. You can also search for BC Wallet in your phone's apps store.

**2. Complete the setup**
Complete the onboarding process and setup up your PIN.

### BC Wallet app URLs
Apple app store URL: https://apps.apple.com/us/app/bc-wallet/id1587380443 
Google play URL: https://play.google.com/store/apps/details?id=ca.bc.gov.BCWallet 

### Please see wireframes:
https://xd.adobe.com/view/c92660d6-7fa9-4a97-bd93-5a2f53d5e685-9c75/ 

### Acceptance Criteria

Given a Person is on their desktop
When they select to download BC Wallet
Then they are presented with the content as described in the Content (desktop) section
And a QR code is displayed that links to the appropriate application store

Given a Person is on their mobile
When they select to download BC Wallet
Then they are presented with the content as described in the Content (desktop) section

Given a Person has selected the BC Wallet to download
When they select either the the App Store or Google Play
Then the respective app store will open on their device

**Comment by knguyenBC** [comment]
@alexgmetcalf content added

**Comment by knguyenBC** [comment]
@wadeking98 Added the appstore URLS for iOS and google
