### ISSUE TITLE
Change web preview image to say "showcase" instead of "demo"

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/BC-Wallet-Demo#57]
New preview image: ![Artboard 1-100.jpg](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/6d611352-3789-411d-9c46-743e83738ce6)

**Comment by knguyenBC** [comment]
@alexgmetcalf here you go!

**Comment by wadeking98** [comment]
PR: https://github.com/bcgov/BC-Wallet-Demo/pull/62
