### ISSUE TITLE
Need to ensure user is using demo site on different device than wallet

### ISSUE THREAD

**Issue by alexgmetcalf** [bcgov/BC-Wallet-Demo#60]
Since deep linking may not be ready for M2, we need to ensure the user is browsing the demo site on a different device than they have BC Wallet on.

Suggest we do two things:
- Change the up-front description to make sure they're on a different device
- Hide the same-device links that would ordinarily appear below the QR codes

Anything else? @cvarjao @wadeking98

**Comment by cvarjao** [comment]
@alexgmetcalf, it is in the works. I should be ready

**Comment by wadeking98** [comment]
Deep linking is now supported
