### ISSUE TITLE
Update showcase preview image

### ISSUE THREAD

**Issue by alexgmetcalf** [bcgov/BC-Wallet-Demo#72]
Replace showcase preview image with this one please.

![BC-Wallet-showcase-preview-image.jpeg](https://images.zenhubusercontent.com/5fc12a41655018f9efa6b04c/c0d90c1b-344f-4fcb-87ef-13c95335a852)

**Comment by wadeking98** [comment]
resolved by: https://github.com/bcgov/BC-Wallet-Demo/pull/71
