### ISSUE TITLE
Lawyer Showcase v2

### ISSUE THREAD

**Issue by cvarjao** [bcgov/BC-Wallet-Demo#84]
We need a separate version of the lawyer showcase, one that demonstrates how VP might work in conjunction with the LSBC VC.

It could eventually live at /showcase/lawyer2 or similar.

It will not replace nor affect the lawyer showcase that solely uses the LSBC VC.

Please could this second version be set up, even with dev / staging URLs for now.

**Comment by alexgmetcalf** [comment]
@wadeking98 Clecio is going to reach out to you about this

**Comment by wadeking98** [comment]
deployed at: https://bc-wallet-demo-dev.apps.silver.devops.gov.bc.ca/digital-trust/showcase/lawyer2
assigning to Alex and Kim for UX work

**Comment by hannahgov** [comment]
[Mural board ](https://app.mural.co/t/digitalidentityandtrust0399/m/digitalidentityandtrust0399/1666280189047/211ffe0c9036c7987b551dd096f9c29d6b7ef1fb?wid=0-1666797326398)for rough draft

**Comment by hannahgov** [comment]
[Content document](https://docs.google.com/document/d/1c2uLjbGbcUIi8nMf97D0IN9cB3c5xQ9WdLT7t3sGL2c/edit?usp=sharing)

**Comment by wadeking98** [comment]
Resolved by: https://github.com/bcgov/BC-Wallet-Demo/pull/116
