### ISSUE TITLE
VP Showcase

### ISSUE THREAD

**Issue by alexgmetcalf** [bcgov/BC-Wallet-Demo#86]
We need to create a separate version of the showcase that lets you present a real VP to a fictitious verifier. The user would already have a VP coming into the showcase, so all the showcase needs is a single verification journey. This needs to be completed for end of October.

See user flow
https://app.mural.co/t/digitalidentityandtrust0399/m/digitalidentityandtrust0399/1666280189047/211ffe0c9036c7987b551dd096f9c29d6b7ef1fb?sender=kimberlynguyen7757

**Comment by wadeking98** [comment]
live in dev: https://bc-wallet-demo-dev.apps.silver.devops.gov.bc.ca/digital-trust/showcase/demo/person assigning to @hannahgov for UI/UX work

**Comment by wadeking98** [comment]
I think this issue has been replaced by the person/lsbc demo: https://digital.gov.bc.ca/digital-trust/showcase/demo/joyce
Can someone please confirm?

**Comment by hannahgov** [comment]
> I think this issue has been replaced by the person/lsbc demo: https://digital.gov.bc.ca/digital-trust/showcase/demo/joyce Can someone please confirm?

I believe so? At least we don't need a Showcase for only the VP right now
