### ISSUE TITLE
Implement GDX Web Analytics

### ISSUE THREAD

**Issue by cvarjao** [bcgov/BC-Wallet-Demo#88]
- Implement tracking code
- Coordinate with GDX team to get the dashboard setup
   - Clecio, Hannah, Kim, Charles

**Comment by nodlesh** [comment]
@wadeking98 Is this testable at this time, ie, is the dashboard setup, or can we just close this?

**Comment by nodlesh** [comment]
@wadeking98 Check my last comment. 👆
