### ISSUE TITLE
Review/Update Issuer and Verifier names in the Lawyer v1 showcase

### ISSUE THREAD

**Issue by cvarjao** [bcgov/BC-Wallet-Demo#94]

**Comment by wadeking98** [comment]
Are we still planning on using lawyer v1? it seems like eveything is moving to lawyer2 (joyce)

**Comment by hannahgov** [comment]
I agree everything is now joyce

**Comment by knguyenBC** [comment]
Old ticket that references an old version of the lawyer showcase. Closing
