### ISSUE TITLE
Fix spelling in content

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/BC-Wallet-Demo#97]
See changes highlighted in green in the [content document](https://docs.google.com/document/d/1c2uLjbGbcUIi8nMf97D0IN9cB3c5xQ9WdLT7t3sGL2c/edit?usp=sharing).

- LSBC -> Law Society of British Columbia
- CSB -> Court Services Branch
- Verified Person -> Person credential
- Lawyer2 -> Joyce
- Ensure all sentences end in a period
- Headers should only have the first word capitalize (unless other words are pronouns ex. Get your Law Society of British Columbia credential)

Basically spell out all abbreviations unless it's a pronoun. 
ex. BC Wallet, BC Services Card are all pronouns.

### Screenshots below
![Screen Shot 2022-11-01 at 9.15.31 AM.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/4885d93e-7cf5-4724-8cd1-e6807c8978a6)

![Screen Shot 2022-11-01 at 9.22.29 AM.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/3c0984b6-c9cc-47db-ba5d-e3e4b95834c1)

![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/e07c6f73-ebc8-4f31-8217-fdd68e363312)

![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/511248f8-8bb5-40f8-ad43-dcbcbdefaf0c)

![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/2693e84f-8bc2-4b8a-885a-05f89fc9d6fe)
Fix capitalization, spell out acronyms. missing period.

**Comment by wadeking98** [comment]
Resolved by: https://github.com/bcgov/BC-Wallet-Demo/pull/116
