### ISSUE TITLE
Change content in BC Wallet download pop up

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/BC-Wallet-Demo#99]
See changes highlighted in green in the [content document](https://docs.google.com/document/d/1c2uLjbGbcUIi8nMf97D0IN9cB3c5xQ9WdLT7t3sGL2c/edit#heading=h.dmpzhilg0ia8)

Scroll down to bottom for this content changes.

**Comment by wadeking98** [comment]
Resolved by: https://github.com/bcgov/BC-Wallet-Demo/pull/116
